[
  {
    "id" : "c8894d28-2917-415f-a96b-5a7f302285be",
    "prId" : 763,
    "comments" : [
      {
        "id" : "3ef68b37-efb5-4bc6-961e-89576b51fc24",
        "parentId" : null,
        "author" : {
          "login" : "gabro",
          "name" : null,
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/691940?u=5aaf176f5da60764f857b8f8c6842217f737627f&v=4"
        },
        "body" : "I don't know enough about how this is used to understand how to fix it.\r\n\r\n`ControlThrowable` has been made an abstract class in 2.13, so we can't mix it in this way anymore. See a relevant discussion at https://github.com/scala/bug/issues/11494",
        "createdAt" : "2019-06-13T11:17:25Z",
        "updatedAt" : "2019-06-18T18:13:44Z",
        "lastEditedBy" : {
          "login" : "gabro",
          "name" : null,
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/691940?u=5aaf176f5da60764f857b8f8c6842217f737627f&v=4"
        },
        "tags" : [
          {
            "value" : "outdated"
          }
        ]
      }
    ],
    "commit" : "8b8f8c663ffe7481455869fe747514f96e7e658b",
    "line" : null,
    "diffHunk" : "@@ -8,7 +8,7 @@ import scala.util.control.ControlThrowable\n  */\n class ControlCancellationException(\n     cause: CancellationException = new CancellationException()\n-) extends CancellationException(cause.getMessage)\n-    with ControlThrowable {\n+) extends CancellationException(cause.getMessage) {\n+  // with ControlThrowable { // TODO(gabro)"
  }
]