[{
  "comments": [{
    "author": {
      "login": "cloud-fan"
    },
    "body": "we can revert this after revert the error message change.\n",
    "commit": "b600089d4736e9768a8968fb4dead08d28014ac1",
    "createdAt": "2016-01-29T07:48:40Z",
    "diffHunk": "@@ -270,7 +270,8 @@ class AnalysisErrorSuite extends AnalysisTest {\n     val error = intercept[AnalysisException] {\n       SimpleAnalyzer.checkAnalysis(join)\n     }\n-    assert(error.message.contains(\"Failure when resolving conflicting references in Join\"))\n+    assert(error.message.contains(\"Failure when resolving conflicting references\\n\" +"
  }],
  "prId": 10630
}]